version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:tap-tester
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            virtualenv -p python3 /usr/local/share/virtualenvs/tap-s3-csv
            . /usr/local/share/virtualenvs/tap-s3-csv/bin/activate
            pip3 install .[test]
      - run:
          name: 'Pylinting'
          command: |
            . /usr/local/share/virtualenvs/tap-s3-csv/bin/activate
            pylint --rcfile .pylintrc tap_s3_csv/
      - run:
          name: 'Unit Tests'
          command: |
            . /usr/local/share/virtualenvs/tap-s3-csv/bin/activate
            nosetests tests
      - add_ssh_keys
      - run:
          name: 'Integration Tests'
          command: |
            aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
            aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
            aws s3 cp s3://com-stitchdata-dev-deployment-assets/environments/tap-tester/sandbox dev_env.sh
            source dev_env.sh
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            run-a-test --tap=tap-s3-csv \
                       --target=target-stitch \
                       --orchestrator=stitch-orchestrator \
                       --email=harrison+sandboxtest@stitchdata.com \
                       --password=$SANDBOX_PASSWORD \
                       --client-id=50 \
                       tap_tester.suites.s3_csv
